### ISSUE TITLE
tests broken after updating to meteor 1.3

### ISSUE THREAD

**Issue by ashersz** [damirkusar/catena-generator#1]
I updated meteor to 1.3 and the jasmine server did not start
I20160405-08:29:55.666(3)? [velocity] jasmine-server-integration is starting a mirror at http://localhost:51226/.
I20160405-08:29:55.668(3)? [velocity] You can see the mirror logs at: tail -f /Volumes/code/ezratisrael/.meteor/local/log/jasmine-server-integration.log
W20160405-08:29:59.589(3)? (STDERR) [sanjo:karma]: start request failed { [Error: connect ECONNREFUSED]
W20160405-08:29:59.589(3)? (STDERR)   code: 'ECONNREFUSED',
W20160405-08:29:59.590(3)? (STDERR)   errno: 'ECONNREFUSED',
W20160405-08:29:59.590(3)? (STDERR)   syscall: 'connect' }
the log says
tail -f /Volumes/code/ezratisrael/.meteor/local/log/jasmine-server-integration.log
=> Using velocity:METEOR@1.2.1_2 as requested (overriding Meteor 1.3)

[[[[[ /Volumes/code/ezratisrael ]]]]]

=> Started proxy.
Parent process ( 25602 ) is dead! Exiting jasmine-server-integration

I then updated sanjo:jasmine to 1.0.0 but it did not help
Do you know what I should do to have the tests running? 
Thanks for this very good code generator

**Comment by damirkusar** [comment]
Hopefully you solved the issue.. 
Closing because it is very old and project is deprecated.
